#!/bin/bash
# Generate dummy packageMetadata.ts if it doesn't exist
# This is a workaround for the circular dependency issue with typed-message plugin

FILE="src/generated/packageMetadata.ts"

if [ ! -f "$FILE" ]; then
  mkdir -p "$(dirname "$FILE")"
  cat > "$FILE" << 'EOF'
// This file is auto-generated by screw-up plugin
// Do not edit manually

export const name = "";
export const version = "";
export const description = "";
export const author = "";
export const license = "";
export const repository_url = "";
export const git_commit_hash = "";
EOF
  echo "Generated dummy $FILE"
fi
